### ISSUE TITLE
Error: Cannot find module '.../node_modules/node-sass/node_modules/pangyp/bin/node-gyp' during `maji new` on OS X 10.11

### ISSUE THREAD

**Issue by bazzel** [kabisa/maji#77]
```
$ node -v
v5.0.0
$ npm -v
3.3.9
$ maji new org.example.my-awesome-app my-app/
```

During the process, the following error is shown:
```
> node-sass@2.0.1 postinstall /Users/patrickbaselier/code/sandbox/my-app/node_modules/node-sass
> node scripts/build.js

module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/patrickbaselier/code/sandbox/my-app/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
Build failed
```

`maji new` seems to finish without errors, though.

**Comment by pascalw** [comment]
This is probably related to npm3 that no longer automatically installs peer dependencies. Probably `node-sass` was specifying pangu as a peer dependency so we should upgrade `node-sass`.

In general it's probably safe to assume that Maji is currently not npm 3 compatible.
