### ISSUE TITLE
"Error: Cannot find module 'acorn/dist/walk'" when running `make watch` on Mac OS X 10.11

### ISSUE THREAD

**Issue by bazzel** [kabisa/maji#78]
## Steps to reproduce
```
$ node -v
v5.0.0
$ npm -v
3.3.9
$ maji new org.example.my-awesome-app my-app/
$ cd my-app
$ bin/setup
$ make watch
```

The following error occurs:
```
module.js:339
    throw err;
    ^

Error: Cannot find module 'acorn/dist/walk'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/patrickbaselier/code/sandbox/my-app/node_modules/detective/index.js:2:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

The process continues and the log says that the server is up and running.

## To solve this issue

```
$ npm install acorn
$ make watch
```

Adding `acorn` to `package.json` before running `npm install` still gives an error!

**Comment by pascalw** [comment]
This is probably related to npm3 that no longer automatically installs peer dependencies.
In general it's probably safe to assume that Maji is currently not npm 3 compatible.
